version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: loop-it-postgres
    environment:
      POSTGRES_DB: loop-it
      POSTGRES_USER: loop_user
      POSTGRES_PASSWORD: loop_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loop_user -d loop-it"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: