apiVersion: v2
name: loopit-monitoring
description: A complete monitoring stack for Loop-It application with Prometheus, Grafana, Loki, and Promtail
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/Loop-It-Project/Loop-It
sources:
  - https://github.com/Loop-It-Project/Loop-It
maintainers:
  - name: Loop-It DevOps Team
    email: devops@loop-it.com
keywords:
  - monitoring
  - prometheus
  - grafana
  - loki
  - promtail
  - observability
  - kubernetes
annotations:
  category: monitoring
dependencies:
  - name: promtail
    version: "6.17.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: promtail.enabled
