# Monitoring Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "loopit-monitoring.namespace" . }}
  labels:
    {{- include "loopit-monitoring.labels" . | nindent 4 }}
    name: {{ include "loopit-monitoring.namespace" . }}
    app.kubernetes.io/component: namespace
    # Für NetworkPolicies
    monitoring: "true"
    # Für Service Discovery
    prometheus.io/monitoring: "true"
  annotations:
    {{- include "loopit-monitoring.annotations" . | nindent 4 }}
    description: "Loop-It Monitoring Stack - Prometheus, Grafana, Loki, Promtail"
    contact: "devops@loop-it.com"
    created-by: "Loop-It DevOps Team"
    monitoring.coreos.com/enabled: "true"