apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: backend
      app.kubernetes.io/part-of: loop-it
      app.kubernetes.io/component: api

images:
  - name: loop-it-backend
    newTag: latest
