apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
    name: http