# Frontend Deployment with NGINX Volume Fix
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: loopit-dev
  labels:
    app: frontend
    version: v1
spec:
  replicas: 2 # Basis für HPA
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
        - name: frontend
          image: loopit/frontend:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

          # Optimierte Health Checks
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10 # Reduziert von ursprünglich
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3

          # Resource-Optimierung für HPA
          resources:
            requests:
              cpu: 50m # Frontend ist weniger ressourcenintensiv
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

          # ✅ FIX: Volume Mounts für NGINX Verzeichnisse
          volumeMounts:
            - name: cache-volume
              mountPath: /var/cache/nginx
            - name: run-volume
              mountPath: /var/run

          # ✅ FIX: Security Context ohne readOnlyRootFilesystem
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
            # readOnlyRootFilesystem: false # Entfernt für NGINX Compatibility

      # ✅ FIX: Volumes für NGINX
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}

---
# Frontend Service (unverändert)
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: loopit-dev
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: frontend

---
# Frontend HPA (Production-optimiert)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: loopit-dev
  labels:
    app: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 10

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60 # Frontend weniger CPU-intensiv
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
      selectPolicy: Min

---
# Frontend Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: loopit-dev
  labels:
    app: frontend
spec:
  minAvailable: 1 # Mindestens 1 Frontend verfügbar
  selector:
    matchLabels:
      app: frontend
  unhealthyPodEvictionPolicy: AlwaysAllow
