apiVersion: v1
kind: Namespace
metadata:
  name: loopit-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: loopit-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "loop-it"
        - name: POSTGRES_USER
          value: "loop_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: loopit-secrets
              key: postgres-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: loopit-dev
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432