apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loopit-dev

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - ingress.yaml
  - ../../base/backend
  - ../../base/frontend

images:
  - name: loop-it-backend
    newName: vinjust/loop-it-backend
    newTag: 1ba3cba7a6711a08155860bbb885e813163df2ba
  - name: loop-it-frontend
    newName: vinjust/loop-it-frontend
    newTag: 1ba3cba7a6711a08155860bbb885e813163df2ba

labels:
  - includeSelectors: true
    pairs:
      environment: development
      managed-by: argocd
