apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loopit-dev

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - ingress.yaml
  - ../../base/backend
  - ../../base/frontend

images:
  - name: loop-it-backend
    newName: vinjust/loop-it-backend
    newTag: bca7170cf4ddcbf5b2aacfb0ceed662917dddd39
  - name: loop-it-frontend
    newName: vinjust/loop-it-frontend
    newTag: bca7170cf4ddcbf5b2aacfb0ceed662917dddd39

labels:
  - includeSelectors: true
    pairs:
      environment: development
      managed-by: argocd
