apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loopit-dev

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - ingress.yaml
  - ../../base/backend
  - ../../base/frontend

images:
  - name: loop-it-backend
    newName: vinjust/loop-it-backend
    newTag: 6f3218e0452d18518f5630fd943b945e4e909236
  - name: loop-it-frontend
    newName: vinjust/loop-it-frontend
    newTag: 6f3218e0452d18518f5630fd943b945e4e909236

labels:
  - includeSelectors: true
    pairs:
      environment: development
      managed-by: argocd
