apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loopit-dev

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - ingress.yaml
  - ../../base/backend
  - ../../base/frontend

images:
  - name: loop-it-backend
    newName: vinjust/loop-it-backend
    newTag: b1420a8197d7889a50c4b7c583106d24cc7740be
  - name: loop-it-frontend
    newName: vinjust/loop-it-frontend
    newTag: b1420a8197d7889a50c4b7c583106d24cc7740be

labels:
  - includeSelectors: true
    pairs:
      environment: development
      managed-by: argocd
