apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loopit-dev

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - ingress.yaml
  - ../../base/backend
  - ../../base/frontend

images:
  - name: loop-it-backend
    newName: vinjust/loop-it-backend
    newTag: f38e1ebafe3b05976c82aec914161fce149239a6
  - name: loop-it-frontend
    newName: vinjust/loop-it-frontend
    newTag: f38e1ebafe3b05976c82aec914161fce149239a6

labels:
  - includeSelectors: true
    pairs:
      environment: development
      managed-by: argocd
