apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loopit-dev

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - ingress.yaml
  - ../../base/backend
  - ../../base/frontend

images:
  - name: loop-it-backend
    newName: vinjust/loop-it-backend
    newTag: 603fef8a05563f4cdbcce2afe13623bf015034fb
  - name: loop-it-frontend
    newName: vinjust/loop-it-frontend
    newTag: 603fef8a05563f4cdbcce2afe13623bf015034fb

labels:
  - includeSelectors: true
    pairs:
      environment: development
      managed-by: argocd
