apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loopit-dev

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - ingress.yaml
  - ../../base/backend
  - ../../base/frontend

images:
  - name: loop-it-backend
    newName: vinjust/loop-it-backend
    newTag: e4c6dfd7e2639db83bab5e74073cf74965bebcd5
  - name: loop-it-frontend
    newName: vinjust/loop-it-frontend
    newTag: e4c6dfd7e2639db83bab5e74073cf74965bebcd5

labels:
  - includeSelectors: true
    pairs:
      environment: development
      managed-by: argocd
