# gitops/base/frontend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    component: web
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
