{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loop-it.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loop-it.frontend.labels" . | nindent 4 }}
  {{- with (include "loop-it.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "loop-it.frontend.selectorLabels" . | nindent 4 }}
{{- end }}