name: Backend CI

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      
      - name: Check Node Version
        run: node --version

      - name: Install Dependencies
        run: npm ci

      - name: Check for Vulnerabilities
        run: npm audit --audit-level=high
# Backend needs adjustment for build step
#      - name: Build Backend
#       run: npm run build